package org.runestar.client.api.web.hiscore

enum class HiscoreCategory(val label: String) {
    OVERALL("Overall"),
    ATTACK("Attack"),
    DEFENCE("Defence"),
    STRENGTH("Strength"),
    HITPOINTS("Hitpoints"),
    RANGED("Ranged"),
    PRAYER("Prayer"),
    MAGIC("Magic"),
    COOKING("Cooking"),
    WOODCUTTING("Woodcutting"),
    FLETCHING("Fletching"),
    FISHING("Fishing"),
    FIREMAKING("Firemaking"),
    CRAFTING("Crafting"),
    SMITHING("Smithing"),
    MINING("Mining"),
    HERBLORE("Herblore"),
    AGILITY("Agility"),
    THIEVING("Thieving"),
    SLAYER("Slayer"),
    FARMING("Farming"),
    RUNECRAFT("Runecraft"),
    HUNTER("Hunter"),
    CONSTRUCTION("Construction"),
    LEAGUE_POINTS("League Points"),
    BOUNTY_HUNTER_HUNTER("Bounty Hunter - Hunter"),
    BOUNTY_HUNTER_ROGUE("Bounty Hunter - Rogue"),
    CLUE_SCROLL_ALL("Clue Scrolls (all)"),
    CLUE_SCROLL_BEGINNER("Clue Scrolls (beginner)"),
    CLUE_SCROLL_EASY("Clue Scrolls (easy)"),
    CLUE_SCROLL_MEDIUM("Clue Scrolls (medium)"),
    CLUE_SCROLL_HARD("Clue Scrolls (hard)"),
    CLUE_SCROLL_ELITE("Clue Scrolls (elite)"),
    CLUE_SCROLL_MASTER("Clue Scrolls (master)"),
    LAST_MAN_STANDING("Last Man Standing"),
    ABYSSAL_SIRE("Abyssal Sire"),
    ALCHEMICAL_HYDRA("Alchemical Hydra"),
    BARROWS_CHESTS("Barrows Chests"),
    BRYOPHYTA("Bryophyta"),
    CALLISTO("Callisto"),
    CERBERUS("Cerberus"),
    CHAMBERS_OF_XERIC("Chambers of Xeric"),
    CHAMBERS_OF_XERIC_CHALLENGE_MODE("Chambers of Xeric: Challenge Mode"),
    CHAOS_ELEMENTAL("Chaos Elemental"),
    CHAOS_FANATIC("Chaos Fanatic"),
    COMMANDER_ZILYANA("Commander Zilyana"),
    CORPOREAL_BEAST("Corporeal Beast"),
    CRAZY_ARCHAEOLOGIST("Crazy Archaeologist"),
    DAGANNOTH_PRIME("Dagannoth Prime"),
    DAGANNOTH_REX("Dagannoth Rex"),
    DAGANNOTH_SUPREME("Dagannoth Supreme"),
    DERANGED_ARCHAEOLOGIST("Deranged Archaeologist"),
    GENERAL_GRAARDOR("General Graardor"),
    GIANT_MOLE("Giant Mole"),
    GROTESQUE_GUARDIANS("Grotesque Guardians"),
    HESPORI("Hespori"),
    KALPHITE_QUEEN("Kalphite Queen"),
    KING_BLACK_DRAGON("King Black Dragon"),
    KRAKEN("Kraken"),
    KREEARRA("Kree'Arra"),
    KRIL_TSUTSAROTH("K'ril Tsutsaroth"),
    MIMIC("Mimic"),
    NIGHTMARE("Nightmare"),
    OBOR("Obor"),
    SARACHNIS("Sarachnis"),
    SCORPIA("Scorpia"),
    SKOTIZO("Skotizo"),
    THE_GAUNTLET("The Gauntlet"),
    THE_CORRUPTED_GAUNTLET("The Corrupted Gauntlet"),
    THEATRE_OF_BLOOD("Theatre of Blood"),
    THERMONUCLEAR_SMOKE_DEVIL("Thermonuclear Smoke Devil"),
    TZKAL_ZUK("TzKal-Zuk"),
    TZTOK_JAD("TzTok-Jad"),
    VENENATIS("Venenatis"),
    VETION("Vet'ion"),
    VORKATH("Vorkath"),
    WINTERTODT("Wintertodt"),
    ZALCANO("Zalcano"),
    ZULRAH("Zulrah"),
    ;
}
